spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:

  flyway:
    enabled: true
    locations: classpath:db/migration
    check-location: true
    baseline-on-migrate: true